# Experiment preference matching

Was from Phil's session, which assumes nobody has to do cosmic watch as a primary experiment. Math would need adjusting slightly for other sessions

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# "0" corresponds to "Compton Scattering", "10" corresponds to "Optical Trapping" etc
experiments = np.array(["Compton Scattering", 
                "Frank-Hertz",
                "Relativistic Dynamics", 
                "Pulsed NMR: Spin Echoes",
                "The Speed and Mean Life of Cosmic-Ray Muons",
                "Rutherford Scattering",
                "Optical Emission Spectra of Hydrogenic Atoms",
                "X-Ray Physics",
                "Johnson Noise and Shot Noise",
                "21-cm Radio Astrophysics",
                "Optical Trapping"
                ])

# add the name of one lab partner per group as a means of identifying
group_single_members = np.array(["name1", 
                                "name2",
                                "name3",
                                "name4",
                                "name5",
                                "name6"])


# Preferences copied from canvas, format explained below (random numbers here by default)
preferences = np.array([
  [1,6,2,9,3,10,8,5,7,4,11] ,
  [7,10,11,1,8,4,3,5,2,6,9] ,
  [3,10,4,8,6,2,1,7,5,9,11] ,
  [7,5,6,3,1,8,2,9,11,4,10] ,
  [4,10,2,9,1,5,6,8,3,11,7] ,
  [2,10,1,5,8,4,3,11,9,6,7] ,
])

num_groups = preferences.shape[0]
num_experiments = len(experiments)

max_num_groups_per_experiment = 3
num_experiments_per_group = 3  # 2 if everyone does cosmic watch

In [3]:
preferences[0].argsort()[:2]

array([0, 2], dtype=int64)

In [4]:
preferences[0] # the preferences for group 0. 

# means the "0th" experiment (compton scattering) above is their top choice, relativistic dynamics is second 

array([ 1,  6,  2,  9,  3, 10,  8,  5,  7,  4, 11])

In [5]:
preferences[:,0] # the rankings of each group for the compton scattering experiment

array([1, 7, 3, 7, 4, 2])

### Monte Carlo-based Matching approach

- First of all, assume nobody does cosmic watch, so we have 3 experiments per group for a match. 

- Allowed degeneracies: Each experiment can be taken by 3 groups (in fact, compton could in theory be taken by all 6, that is 2 groups at a time in each of the 3 sessions, but we assume this for simplicity). 

- A "match" has format [ [the 3 experiments group 0 will do] , [the 3 experiments group 1 will do] , ...]

- We then randomly generate matches, test for how well they work by some metric which we call "match_goodness". Run for a while, output the best match you found.

In [6]:
# check if we have to do any work, that is look at everybodies top choices

ideals = np.zeros((num_groups,num_experiments_per_group))

for i in range(num_groups):
    indices_ideal_experiments = preferences[i].argsort()[:num_experiments_per_group]  # indices of two smallest values (highest preference)
    ideals[i] = indices_ideal_experiments

ideals = ideals.astype("int") # sorting messes it up a bit

print(ideals)

[[0 2 4]
 [3 8 6]
 [6 5 0]
 [4 6 3]
 [4 2 8]
 [2 0 6]]


In [7]:
# Check if match is valid
occurrences = np.bincount(ideals.flatten()) # format [num occurrences of 0, ...1, ...2, ...]

if np.sum(occurrences > max_num_groups_per_experiment) == 0:
    print("No matching necessary, their preferences work")
else: 
    print(f"More than {max_num_groups_per_experiment} groups want the same experiment")
    print("Occurrences: ", occurrences)
    print(f"most \"problematic\" experiment is {np.argmax(occurrences)}, " + experiments[np.argmax(occurrences)] + f", with {occurrences.max()} occurrences in the top {num_experiments_per_group} preference data")

More than 3 groups want the same experiment
Occurrences:  [3 0 3 2 3 1 4 0 2]
most "problematic" experiment is 6, Optical Emission Spectra of Hydrogenic Atoms, with 4 occurrences in the top 3 preference data


### Conclusion
No matching algorithm needed. So one person needs to not do experiment 6, maybe replace with 3 or 5 or cosmic watch.

In [8]:
for group_idx in range(num_groups):
    print(f"\nGroup {group_idx} (ft. {group_single_members[group_idx]}) has experiments:")
    print(experiments[ideals[group_idx]])


Group 0 (ft. name1) has experiments:
['Compton Scattering' 'Relativistic Dynamics'
 'The Speed and Mean Life of Cosmic-Ray Muons']

Group 1 (ft. name2) has experiments:
['Pulsed NMR: Spin Echoes' 'Johnson Noise and Shot Noise'
 'Optical Emission Spectra of Hydrogenic Atoms']

Group 2 (ft. name3) has experiments:
['Optical Emission Spectra of Hydrogenic Atoms' 'Rutherford Scattering'
 'Compton Scattering']

Group 3 (ft. name4) has experiments:
['The Speed and Mean Life of Cosmic-Ray Muons'
 'Optical Emission Spectra of Hydrogenic Atoms' 'Pulsed NMR: Spin Echoes']

Group 4 (ft. name5) has experiments:
['The Speed and Mean Life of Cosmic-Ray Muons' 'Relativistic Dynamics'
 'Johnson Noise and Shot Noise']

Group 5 (ft. name6) has experiments:
['Relativistic Dynamics' 'Compton Scattering'
 'Optical Emission Spectra of Hydrogenic Atoms']
